package edgee:native;

world data-collection {
  // for some reason, tinygo requires this include
  // cf https://component-model.bytecodealliance.org/language-support/go.html#2-determine-which-world-the-component-will-implement
  include wasi:cli/imports@0.2.2;
  export edgee:protocols/data-collection;
}
