manifest-version = 1

[component]
name = "example-go-edge-function-component"
version = "1.0.0"
category = "edge-function"
subcategory = "wasm-function"
description = "Example Go component for edge function"
documentation = "https://github.com/edgee-cloud/example-go-component"
repository = "https://github.com/edgee-cloud/example-go-component"
language = "Go"
wit-version = "1.0.0"

[component.build]
command = "go tool wit-bindgen-go generate -o internal/ ./.edgee/wit && tinygo build -target=wasip2 -o component.wasm --wit-package .edgee/wit/ --wit-world edge-function ./"
output_path = "./component.wasm"

[component.settings.example]
title = "Example Config Field"
type = "string"
