manifest-version = 1

[component]
name = "example-go-component"
version = "1.0.0"
category = "consent-management"
subcategory = "consent-mapping"
description = "Example Go component for consent management"
documentation = "https://github.com/edgee-cloud/example-go-component"
repository = "https://github.com/edgee-cloud/example-go-component"
language = "Go"
wit-version = "1.0.0"

[component.build]
command = "go run go.bytecodealliance.org/cmd/wit-bindgen-go generate -o internal/ ./.edgee/wit && tinygo build -target=wasip2 -o cmp_component.wasm --wit-package .edgee/wit/ --wit-world consent-management ./"
output_path = "./cmp_component.wasm"

[component.settings.example]
title = "Example Config Field"
type = "string"
